# .github/workflows/code_reviewer.yml

name: 'Gemini Code Reviewer'

# This action will trigger on every pull request that is opened or synchronized (new commits pushed)
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write # Required to post comments on the PR

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the action can access it
      - name: Checkout Repository
        uses: actions/checkout@v4
        # We need to fetch the full history to get the diff correctly
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install necessary Python packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the review script
      # We pass the Gemini API key and all necessary GitHub context as environment variables
      - name: Run Gemini Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: python .github/scripts/review.py
