# .github/workflows/code_reviewer.yml

name: 'Gemini Code Reviewer'

# This action will trigger on every pull request that is opened or synchronized (new commits pushed)
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write # Required to post comments on the PR

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the action can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install necessary Python packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the review script
      # We pass the Gemini API key as a secret and the GitHub token and PR URL as environment variables
      - name: Run Gemini Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.url }}
        run: python .github/scripts/review.py